// Mocks generated by Mockito 5.4.6 from annotations
// in mealsnap/test/screens/scan_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;
import 'dart:io' as _i10;
import 'dart:ui' as _i11;

import 'package:camera/camera.dart' as _i5;
import 'package:camera_platform_interface/camera_platform_interface.dart'
    as _i4;
import 'package:flutter/foundation.dart' as _i7;
import 'package:flutter/material.dart' as _i6;
import 'package:flutter/services.dart' as _i12;
import 'package:mealsnap/services/gemini_service.dart' as _i3;
import 'package:mealsnap/services/local_recognition_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeLocalLabelResult_0 extends _i1.SmartFake
    implements _i2.LocalLabelResult {
  _FakeLocalLabelResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMealAnalysisResult_1 extends _i1.SmartFake
    implements _i3.MealAnalysisResult {
  _FakeMealAnalysisResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCameraDescription_2 extends _i1.SmartFake
    implements _i4.CameraDescription {
  _FakeCameraDescription_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMediaSettings_3 extends _i1.SmartFake implements _i4.MediaSettings {
  _FakeMediaSettings_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCameraValue_4 extends _i1.SmartFake implements _i5.CameraValue {
  _FakeCameraValue_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeXFile_5 extends _i1.SmartFake implements _i4.XFile {
  _FakeXFile_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWidget_6 extends _i1.SmartFake implements _i6.Widget {
  _FakeWidget_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString({_i7.DiagnosticLevel? minLevel = _i7.DiagnosticLevel.info}) =>
      super.toString();
}

/// A class which mocks [CameraDescription].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockCameraDescription extends _i1.Mock implements _i4.CameraDescription {
  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i8.dummyValue<String>(this, Invocation.getter(#name)),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#name),
            ),
          )
          as String);

  @override
  _i4.CameraLensDirection get lensDirection =>
      (super.noSuchMethod(
            Invocation.getter(#lensDirection),
            returnValue: _i4.CameraLensDirection.front,
            returnValueForMissingStub: _i4.CameraLensDirection.front,
          )
          as _i4.CameraLensDirection);

  @override
  int get sensorOrientation =>
      (super.noSuchMethod(
            Invocation.getter(#sensorOrientation),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i4.CameraLensType get lensType =>
      (super.noSuchMethod(
            Invocation.getter(#lensType),
            returnValue: _i4.CameraLensType.wide,
            returnValueForMissingStub: _i4.CameraLensType.wide,
          )
          as _i4.CameraLensType);
}

/// A class which mocks [LocalRecognitionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalRecognitionService extends _i1.Mock
    implements _i2.LocalRecognitionService {
  @override
  _i9.Future<_i2.LocalLabelResult> recognizeFoodImage(_i10.File? imageFile) =>
      (super.noSuchMethod(
            Invocation.method(#recognizeFoodImage, [imageFile]),
            returnValue: _i9.Future<_i2.LocalLabelResult>.value(
              _FakeLocalLabelResult_0(
                this,
                Invocation.method(#recognizeFoodImage, [imageFile]),
              ),
            ),
            returnValueForMissingStub: _i9.Future<_i2.LocalLabelResult>.value(
              _FakeLocalLabelResult_0(
                this,
                Invocation.method(#recognizeFoodImage, [imageFile]),
              ),
            ),
          )
          as _i9.Future<_i2.LocalLabelResult>);

  @override
  _i9.Future<String> recognizeReceiptText(_i10.File? imageFile) =>
      (super.noSuchMethod(
            Invocation.method(#recognizeReceiptText, [imageFile]),
            returnValue: _i9.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#recognizeReceiptText, [imageFile]),
              ),
            ),
            returnValueForMissingStub: _i9.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#recognizeReceiptText, [imageFile]),
              ),
            ),
          )
          as _i9.Future<String>);

  @override
  _i3.MealAnalysisResult buildFallbackResult(
    _i2.LocalLabelResult? localResult,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#buildFallbackResult, [localResult]),
            returnValue: _FakeMealAnalysisResult_1(
              this,
              Invocation.method(#buildFallbackResult, [localResult]),
            ),
            returnValueForMissingStub: _FakeMealAnalysisResult_1(
              this,
              Invocation.method(#buildFallbackResult, [localResult]),
            ),
          )
          as _i3.MealAnalysisResult);

  @override
  _i9.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}

/// A class which mocks [CameraController].
///
/// See the documentation for Mockito's code generation for more information.
class MockCameraController extends _i1.Mock implements _i5.CameraController {
  @override
  _i4.CameraDescription get description =>
      (super.noSuchMethod(
            Invocation.getter(#description),
            returnValue: _FakeCameraDescription_2(
              this,
              Invocation.getter(#description),
            ),
            returnValueForMissingStub: _FakeCameraDescription_2(
              this,
              Invocation.getter(#description),
            ),
          )
          as _i4.CameraDescription);

  @override
  _i4.ResolutionPreset get resolutionPreset =>
      (super.noSuchMethod(
            Invocation.getter(#resolutionPreset),
            returnValue: _i4.ResolutionPreset.low,
            returnValueForMissingStub: _i4.ResolutionPreset.low,
          )
          as _i4.ResolutionPreset);

  @override
  bool get enableAudio =>
      (super.noSuchMethod(
            Invocation.getter(#enableAudio),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.MediaSettings get mediaSettings =>
      (super.noSuchMethod(
            Invocation.getter(#mediaSettings),
            returnValue: _FakeMediaSettings_3(
              this,
              Invocation.getter(#mediaSettings),
            ),
            returnValueForMissingStub: _FakeMediaSettings_3(
              this,
              Invocation.getter(#mediaSettings),
            ),
          )
          as _i4.MediaSettings);

  @override
  int get cameraId =>
      (super.noSuchMethod(
            Invocation.getter(#cameraId),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i5.CameraValue get value =>
      (super.noSuchMethod(
            Invocation.getter(#value),
            returnValue: _FakeCameraValue_4(this, Invocation.getter(#value)),
            returnValueForMissingStub: _FakeCameraValue_4(
              this,
              Invocation.getter(#value),
            ),
          )
          as _i5.CameraValue);

  @override
  set value(_i5.CameraValue? newValue) => super.noSuchMethod(
    Invocation.setter(#value, newValue),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void debugCheckIsDisposed() => super.noSuchMethod(
    Invocation.method(#debugCheckIsDisposed, []),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> prepareForVideoRecording() =>
      (super.noSuchMethod(
            Invocation.method(#prepareForVideoRecording, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> pausePreview() =>
      (super.noSuchMethod(
            Invocation.method(#pausePreview, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> resumePreview() =>
      (super.noSuchMethod(
            Invocation.method(#resumePreview, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> setDescription(_i4.CameraDescription? description) =>
      (super.noSuchMethod(
            Invocation.method(#setDescription, [description]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i4.XFile> takePicture() =>
      (super.noSuchMethod(
            Invocation.method(#takePicture, []),
            returnValue: _i9.Future<_i4.XFile>.value(
              _FakeXFile_5(this, Invocation.method(#takePicture, [])),
            ),
            returnValueForMissingStub: _i9.Future<_i4.XFile>.value(
              _FakeXFile_5(this, Invocation.method(#takePicture, [])),
            ),
          )
          as _i9.Future<_i4.XFile>);

  @override
  _i9.Future<void> startImageStream(_i5.onLatestImageAvailable? onAvailable) =>
      (super.noSuchMethod(
            Invocation.method(#startImageStream, [onAvailable]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> stopImageStream() =>
      (super.noSuchMethod(
            Invocation.method(#stopImageStream, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> startVideoRecording({
    _i5.onLatestImageAvailable? onAvailable,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#startVideoRecording, [], {
              #onAvailable: onAvailable,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i4.XFile> stopVideoRecording() =>
      (super.noSuchMethod(
            Invocation.method(#stopVideoRecording, []),
            returnValue: _i9.Future<_i4.XFile>.value(
              _FakeXFile_5(this, Invocation.method(#stopVideoRecording, [])),
            ),
            returnValueForMissingStub: _i9.Future<_i4.XFile>.value(
              _FakeXFile_5(this, Invocation.method(#stopVideoRecording, [])),
            ),
          )
          as _i9.Future<_i4.XFile>);

  @override
  _i9.Future<void> pauseVideoRecording() =>
      (super.noSuchMethod(
            Invocation.method(#pauseVideoRecording, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> resumeVideoRecording() =>
      (super.noSuchMethod(
            Invocation.method(#resumeVideoRecording, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i6.Widget buildPreview() =>
      (super.noSuchMethod(
            Invocation.method(#buildPreview, []),
            returnValue: _FakeWidget_6(
              this,
              Invocation.method(#buildPreview, []),
            ),
            returnValueForMissingStub: _FakeWidget_6(
              this,
              Invocation.method(#buildPreview, []),
            ),
          )
          as _i6.Widget);

  @override
  _i9.Future<double> getMaxZoomLevel() =>
      (super.noSuchMethod(
            Invocation.method(#getMaxZoomLevel, []),
            returnValue: _i9.Future<double>.value(0.0),
            returnValueForMissingStub: _i9.Future<double>.value(0.0),
          )
          as _i9.Future<double>);

  @override
  _i9.Future<double> getMinZoomLevel() =>
      (super.noSuchMethod(
            Invocation.method(#getMinZoomLevel, []),
            returnValue: _i9.Future<double>.value(0.0),
            returnValueForMissingStub: _i9.Future<double>.value(0.0),
          )
          as _i9.Future<double>);

  @override
  _i9.Future<void> setZoomLevel(double? zoom) =>
      (super.noSuchMethod(
            Invocation.method(#setZoomLevel, [zoom]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> setFlashMode(_i4.FlashMode? mode) =>
      (super.noSuchMethod(
            Invocation.method(#setFlashMode, [mode]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> setExposureMode(_i4.ExposureMode? mode) =>
      (super.noSuchMethod(
            Invocation.method(#setExposureMode, [mode]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> setExposurePoint(_i11.Offset? point) =>
      (super.noSuchMethod(
            Invocation.method(#setExposurePoint, [point]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<double> getMinExposureOffset() =>
      (super.noSuchMethod(
            Invocation.method(#getMinExposureOffset, []),
            returnValue: _i9.Future<double>.value(0.0),
            returnValueForMissingStub: _i9.Future<double>.value(0.0),
          )
          as _i9.Future<double>);

  @override
  _i9.Future<double> getMaxExposureOffset() =>
      (super.noSuchMethod(
            Invocation.method(#getMaxExposureOffset, []),
            returnValue: _i9.Future<double>.value(0.0),
            returnValueForMissingStub: _i9.Future<double>.value(0.0),
          )
          as _i9.Future<double>);

  @override
  _i9.Future<double> getExposureOffsetStepSize() =>
      (super.noSuchMethod(
            Invocation.method(#getExposureOffsetStepSize, []),
            returnValue: _i9.Future<double>.value(0.0),
            returnValueForMissingStub: _i9.Future<double>.value(0.0),
          )
          as _i9.Future<double>);

  @override
  _i9.Future<double> setExposureOffset(double? offset) =>
      (super.noSuchMethod(
            Invocation.method(#setExposureOffset, [offset]),
            returnValue: _i9.Future<double>.value(0.0),
            returnValueForMissingStub: _i9.Future<double>.value(0.0),
          )
          as _i9.Future<double>);

  @override
  _i9.Future<void> lockCaptureOrientation([
    _i12.DeviceOrientation? orientation,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#lockCaptureOrientation, [orientation]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> setFocusMode(_i4.FocusMode? mode) =>
      (super.noSuchMethod(
            Invocation.method(#setFocusMode, [mode]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> unlockCaptureOrientation() =>
      (super.noSuchMethod(
            Invocation.method(#unlockCaptureOrientation, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> setFocusPoint(_i11.Offset? point) =>
      (super.noSuchMethod(
            Invocation.method(#setFocusPoint, [point]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
