// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxl10ov601hV2nKoIdkkt0Cugl6vmG_1s',
    appId: '1:66459851150:web:391bc63f979496f51decdf',
    messagingSenderId: '66459851150',
    projectId: 'studio-5313440936-d8e45',
    authDomain: 'studio-5313440936-d8e45.firebaseapp.com',
    storageBucket: 'studio-5313440936-d8e45.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHMSug_tbCDwhy1-blqtpVu6nHBX7-S0Q',
    appId: '1:66459851150:android:d686938f545dbc101decdf',
    messagingSenderId: '66459851150',
    projectId: 'studio-5313440936-d8e45',
    storageBucket: 'studio-5313440936-d8e45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAodMlpYWHoV9iuJvJymhM0EtbBgG7TQ6U',
    appId: '1:66459851150:ios:a33f62956f4709861decdf',
    messagingSenderId: '66459851150',
    projectId: 'studio-5313440936-d8e45',
    storageBucket: 'studio-5313440936-d8e45.firebasestorage.app',
    iosBundleId: 'com.example.mealsnap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAodMlpYWHoV9iuJvJymhM0EtbBgG7TQ6U',
    appId: '1:66459851150:ios:a33f62956f4709861decdf',
    messagingSenderId: '66459851150',
    projectId: 'studio-5313440936-d8e45',
    storageBucket: 'studio-5313440936-d8e45.firebasestorage.app',
    iosBundleId: 'com.example.mealsnap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxl10ov601hV2nKoIdkkt0Cugl6vmG_1s',
    appId: '1:66459851150:web:58f750ad9fe176a01decdf',
    messagingSenderId: '66459851150',
    projectId: 'studio-5313440936-d8e45',
    authDomain: 'studio-5313440936-d8e45.firebaseapp.com',
    storageBucket: 'studio-5313440936-d8e45.firebasestorage.app',
  );
}
